global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '3.231.163.219:9100'
          - ':9100'
          - ':9100'
          - ':9100'

  - job_name: 'flask-api'
    metrics_path: '/health'
    static_configs:
      - targets: [':30500']
