global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  - "alert.rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        refresh_interval: 10s
        filters:
          - name: tag:Project
            values: ['infrarevive']
          - name: tag:Role
            values: ['master', 'worker']
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: '$1:9100'
