[jenkins]
44.204.213.150 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem

[k8s_master]
44.192.111.39 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem

[k8s_workers]
98.92.144.101 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
100.61.137.58 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
3.92.74.195 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
