[jenkins]
3.237.238.136 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem

[k8s_master]
44.193.79.60 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem

[k8s_workers]
100.58.215.236 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
3.232.132.208 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
44.214.42.242 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
