[jenkins]
44.204.133.225 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem

[k8s_master]
3.236.194.83 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem

[k8s_workers]
32.196.230.40 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
32.197.51.116 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
44.213.103.49 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/infrarevive-key.pem
